`timescale 1ns / 1ps

module keccak_round_tb;

    // DUT signals
    reg  [1599:0] state_in;
    reg  [4:0]    round_num;
    wire [1599:0] state_out;

    // Instantiate DUT
    keccak_round uut (
        .state_in  (state_in),
        .round     (round_num),
        .state_out (state_out)
    );

    // Reference vectors: 24 rounds x 25 lanes = 600 entries
    // Generated by gen_round_vectors.cpp
    reg [63:0] expected_lanes [0:599];

    // Working variables
    reg [1599:0] chain_state;
    reg [1599:0] expected_state;
    integer i, j, errors;

    // Display all 25 lanes of a 1600-bit state
    task display_state;
        input [1599:0] s;
        integer k;
        begin
            for (k = 0; k < 25; k = k + 1)
                $display("  Lane[%2d] = %h", k, s[k*64 +: 64]);
        end
    endtask

    initial begin
        $dumpfile("keccak_round_tb.vcd");
        $dumpvars(0, keccak_round_tb);

        errors = 0;

        // ==========================================================
        // Test 1: All-zero state, round 0 (analytical verification)
        //
        // For zero input:
        //   theta:  C[x]=0 for all x, so t[x]=0, theta output = 0
        //   rho+pi: rotating zeros = zeros
        //   chi:    0 ^ (~0 & 0) = 0
        //   iota:   lane[0] ^= RC[0] = 0x0000000000000001
        //
        // Expected: lane[0] = 0x0000000000000001, all others = 0
        // ==========================================================
        $display("=== Test 1: All-zero state, round 0 (analytical) ===");
        state_in  = 1600'd0;
        round_num = 5'd0;
        #10;

        begin : test1_block
            reg test1_pass;
            test1_pass = 1;

            if (state_out[63:0] !== 64'h0000000000000001) begin
                $display("FAIL: Lane[0] expected 0000000000000001, got %h",
                         state_out[63:0]);
                test1_pass = 0;
            end

            for (i = 1; i < 25; i = i + 1) begin
                if (state_out[i*64 +: 64] !== 64'h0) begin
                    $display("FAIL: Lane[%0d] expected 0, got %h",
                             i, state_out[i*64 +: 64]);
                    test1_pass = 0;
                end
            end

            if (test1_pass)
                $display("PASS");
            else
                errors = errors + 1;
        end

        // ==========================================================
        // Test 2: Chain all 24 rounds starting from all-zeros.
        // Compare each round's output with C++ reference vectors
        // loaded from round_vectors.hex.
        //
        // To generate the hex file, compile and run gen_round_vectors.cpp:
        //   g++ -o gen_round_vectors gen_round_vectors.cpp && ./gen_round_vectors
        //
        // The full chain computes keccak_f1600(0), exercising every
        // round with increasingly complex state.
        // ==========================================================
        $display("\n=== Test 2: 24-round chain vs C++ reference ===");
        $readmemh("round_vectors.hex", expected_lanes);

        chain_state = 1600'd0;

        for (i = 0; i < 24; i = i + 1) begin
            state_in  = chain_state;
            round_num = i[4:0];
            #10;

            // Build expected 1600-bit state from loaded lanes
            expected_state = 1600'd0;
            for (j = 0; j < 25; j = j + 1)
                expected_state[j*64 +: 64] = expected_lanes[i*25 + j];

            if (state_out !== expected_state) begin
                $display("FAIL: Round %0d", i);
                $display("  Expected Lane[0] = %h", expected_state[63:0]);
                $display("  Got      Lane[0] = %h", state_out[63:0]);
                errors = errors + 1;
            end else begin
                $display("PASS: Round %2d  Lane[0] = %h", i, state_out[63:0]);
            end

            chain_state = state_out;
        end

        // Print final state for manual inspection
        $display("\nFinal state (keccak_f1600 of all-zeros):");
        display_state(chain_state);

        // ==========================================================
        // Summary
        // ==========================================================
        $display("\n=== Summary ===");
        if (errors == 0)
            $display("ALL TESTS PASSED");
        else
            $display("FAILED: %0d error(s)", errors);

        $finish;
    end

endmodule
